### ISSUE TITLE
No message when PR is valid

### ISSUE THREAD

**Issue by smutel** [Namchee/conventional-pr#26]
Hello,

If I understand the code correctly, the message below https://github.com/Namchee/conventional-pr/blob/fa791774fe84e86356e02923124f99e45ee08ca7/main.go#L226 should be written when the PR is valid.

But if you check this PR: https://github.com/smutel/terraform-provider-netbox/pull/63
- No message is displayed in the PR check
- This PR is not valid in fact ... because it is not link to an issue

**Comment by Namchee** [comment]
Hi, thanks for filing an issue. I'm sorry for the issue you've encountered. 

Since the error log shows nothing, I realized that it's really hard to debug errors when it happens 😅 . I'll try to be honest here, I haven't done any thorough test on my local setup as I lack knowledge back then (yeah, this code is almost 1 year old). I'm currently planning to rewrite this tool in near future.

We need to log the error for debugging and I've noticed that you've submitted the PR for it!

Since you've opened #28, I'm going to close this issue and continue the discussion there.
