### ISSUE TITLE
PR links to an issue validation is broken

### ISSUE THREAD

**Issue by Th3S4mur41** [Namchee/conventional-pr#93]
[PR link to an issue](https://github.com/Namchee/conventional-pr?tab=readme-ov-file#pull-request-links-to-an-issue) is reporting success while no issue is either linked or mentioned

See https://github.com/Th3S4mur41/playground/pull/52 for an example

![image](https://github.com/Namchee/conventional-pr/assets/5543595/529c03e5-a1a2-45ce-b379-599f02201f42)
![image](https://github.com/Namchee/conventional-pr/assets/5543595/e446e526-97ce-4726-95dd-0772fa31656f)

**Comment by Namchee** [comment]
Thanks for filing an issue, I'll take a look at this since this is unintended.

**Comment by Namchee** [comment]
Seems like I forgot to re-test this feature when I upgraded the GH library.

**Comment by Namchee** [comment]
After investigation, this issue is caused by the validator using a wrong reference of issue in the pull request data. The issue URL in the pull request data actually always refers to itself, which means the validator will always returns `true` if the validator is enabled.

The solution for this problem is migrating the library to GitHub GraphQL API v4, since it supports [issue referencing](https://github.com/orgs/community/discussions/24367). However, this is not a simple task that can be done in span of hours since I need to migrate everything. This task will be tracked by a separate issue.

In the meantime, I'll fix this problem by searching issue references using [keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) and document the temporary caveats in the documentation.

**Comment by Namchee** [comment]
Sorry for the wait, I've released `v0.14.1`, can you please try the latest version and see if the issue persist with the current limitations?

Currently, you must use closing keywords. Manually linking issue through sidebar isn't supported right now due to API limitations.

**Comment by Th3S4mur41** [comment]
Thanks @Namchee for the quick fix.
Validation is working again 👍

![image](https://github.com/Namchee/conventional-pr/assets/5543595/8ab008be-4145-418d-a455-03d42655e35a)
https://github.com/Th3S4mur41/playground/actions/runs/6610330543/job/17952042847
